#spring:
#  datasource:
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/lab
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
hello:
  message: hello